name: Hola Mundo

on: 
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    hola:
        runs-on: ubuntu-latest
        steps:
            - name: Hola Mundo
              run: echo "Hola Mundo"

            - name: touch file
              run: touch hola.txt

            - name: set text
              run: echo "Hola Mundo" >> hola.txt
            
            - name: Read file
              run: cat hola.txt
    other:
        runs-on: ubuntu-latest
        needs: [hola]
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.7     

            - name: LS
              run: ls -al

            - name: Setup Node.js enviroment
              uses: actions/setup-node@v4.0.3              
              with:
                node-version: latest

            - name: node version
              run: node --version
            
            - name: PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.3'
            
            - name: php version
              run: php --version

    test-build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v2     

            - name: ls
              run: |
                chmod +x script.sh
                ./script.sh
    
    local-action:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run local action
              uses: ./.github/actions/my-action              
              with:
                message: "Fernando"
            - name: SSH
              run: |
                mkdir -p ~/.ssh
                echo "${{secrets.SSH_KEY}}" >> ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan -H 127.0.1.1 >> ~/.ssh/known_hosts
                cat ~/.ssh/known_hosts
    say-hello:
        runs-on: ubuntu-latest
        
        services:
            mysql:
                image: mysql:5.7
                ports:
                    - 3306:3306
                env:
                    MYSQL_ROOT_PASSWORD: example

            redis:
                image: redis
                ports:
                    - 6379:6379
        
        env:
          My_Var: Mi variable de entorno

        steps:
            - name: Test
              run: ls
            
            - name: Variable de entorno
              env:
                Step_My_Var: Nivel step
              run: |
                echo "Valor: $My_Var"
                echo "Valor: $Step_My_Var"
                echo "Valor: ${{ vars.MY_VARIABLE_2 }}"
            
            - name: Secret
              run: |
                echo "Secret: ${{ secrets.MY_SECRET }}"

